### ISSUE TITLE
[BUG] Workspace persistence writes malformed JSON to drive

### ISSUE THREAD

**Issue by MarioFares** [lukasbach/yana#10]
![image](https://user-images.githubusercontent.com/48692032/101385618-b2d54980-38c4-11eb-9438-bb91f2c22ca9.png)

**Comment by lukasbach** [comment]
Hi MarioFares, thank you four your report!

It looks like the issue occured after starting up Yana. Did you use Yana before and sucessfully setup a Yana workspace, or was it after starting up Yana the first time? If you've already setup a workspace, could you kindly send me the contents of the workspace file, named ``notebook.json`` and located at the path you've set when creating the workspace (by default ``C:\Users\Mario\yana-workspace``)? Thanks!

**Comment by MarioFares** [comment]
Yo Lukas how are you man. First of all, big fan. I love Yana and I hope to
switch from Evernote to Yana Permanently.
Now to Business:
-Set up Yana
-Opened it and created some notes
-Closed it and re-opened
-Did not load > I Launched Devtools

Please find notebook.json attached below.

Path: C:\Users\Mario\Desktop\workspace

One more thing, can you please provide me with your email address?
I checked out your website and Yana's features. Got to say I love it. I
myself am going to intern at a web development company and may be I can ask
a few questions now and then
about your learning process and what tech you use.

Thanks,
Mario

**Comment by MarioFares** [comment]
One more thing,
I uninstalled and re-installed on same laptop gave me same error.

I installed on other laptop it worked.

**Comment by lukasbach** [comment]
Hi,

great to hear that you like Yana! My mail-adress is lbach@outlook.de

Looks like you've sent the file via mail to Github and it did not get attached. But I assume that the file just got stored malformed, so it's not that urgent.

Re-installing Yana does not help because your workspaces do not get removed, and stay malformed after reinstallation. If you don't mind loosing changes you've done so far with Yana, you can do the following:

* Remove your workspace (by default located at ``C:\Users\Mario\yana-workspace``, unless you chose a different location)
* Remove your workspaces.json file, located at ``C:\Users\Mario\AppData\Roaming\yana\workspaces.json``

This will reset all application data, and when you then restart Yana, you will have a fresh restart.

My assumption to why that happened is that maybe Yana was writing the file while it was closed, but I'm not sure. I'll add logic to Yana to make that persisting process more resilient. Sorry for the issues.

**Comment by MarioFares** [comment]
{
  "structures": {
    "tags": {},
    "sessionSidebar_a363322e-25c8-4a9d-b42b-acf03bc2d837": [
      "1fc58041-78e6-4159-b7d0-91f23587038b",
      "ba248a04-1dbd-45c5-b9fb-67bb33d5fcb6",
      "ba248a04-1dbd-45c5-b9fb-67bb33d5fcb6",
      "ba248a04-1dbd-45c5-b9fb-67bb33d5fcb6",
      "ba248a04-1dbd-45c5-b9fb-67bb33d5fcb6",
      "ba248a04-1dbd-45c5-b9fb-67bb33d5fcb6",
      "fe9152c0-5859-42b8-8ef4-da6e03a38b70",
      "1e0f0dbe-a169-4bf4-b712-0ac1c9304074"
    ],
    "sessiontabs": {
      "tabs": [
        {
          "page": "__settings"
        }
      ],
      "openTabId": 0
    }
  }
}    "openTabId": 0
    }
  }
}

===
Here you go buddy.
I will do what you told me and reply ASAP.

**Comment by MarioFares** [comment]
I did as you said and reinstalled.
Works good now thanks!

**Comment by lukasbach** [comment]
Great to hear. v1.0.6 also makes persisting more resilient against such errors, hopefully this won't happen in the future. Thanks for your help!
