### ISSUE TITLE
Can't Install on Macbook running on Big Sur

### ISSUE THREAD

**Issue by 1Xavier** [lukasbach/yana#18]
**Describe the bug**
When attempting to install the app on a macbook running on Big Sur 11.1, the following message is displayed on screen:
"Yana" cannot be opened because the developer cannot be verified."

**To Reproduce**
To reproduce, try installing Yana on a macBook running Big Sur 11.1

**Expected behavior**
I expected the app to install.

**Screenshots**
![Yana Error](https://user-images.githubusercontent.com/65773366/103488939-47549e00-4dd6-11eb-96db-85d558e07fec.png)

**Environment (please complete the following information):**
 - OS: Big Sur 11.1
 - Yana Version: Yana-1.0.7-mac.zip (I'm assuming it's version 1.0.7, but just in case they're not related, this is the file name.
 - 
**Additional context**
N/A

**Comment by lukasbach** [comment]
Hi @1Xavier, thanks for your issue!

I'm not a Mac expert, but from what it looks like, macOs requires developers to pay anually for getting apps signed and thus not be catched by gatekeeper, so that's not really something I currently want to do for a free open-source app.

A workaround should work to install the app nevertheless:

1. Open Finder and find the application that gives you the “macOS cannot verify that this app is free from malware” warning message.
2. Control-Click on the application.
3. Access the shortcut menu and click Open. After you do this, the app will be whitelisted and you will be able to open it from now on without getting the “macOS cannot verify that this app is free from malware” warning.
4. Another way to whitelist an app is to click the Open Anyway available in Security & Privacy Preferences. Note that this button would only be available for an hour after you try to open a blocked app. To reach this button, open the Apple Menu, go to System Preferences, click on Security & Privacy, and select General.

Source: https://macresearch.org/macos-cannot-verify-that-this-app-is-free-from-malware/

If you intent to install Yana this way, would you be so kind to give me feedback if that worked? Thanks :)

**Comment by 1Xavier** [comment]
Hey man,
  

  
I really appreciate the follow-up!    I honestly thought my message would go into the void and I’d never hear anything back.    
  

  
I’ll try this out and let you know how it works out.    
  

  
  
  
    
  

  
  
>

**Comment by 1Xavier** [comment]
That worked.  I was able to get Yana installed!

**Comment by lukasbach** [comment]
You're welcome, thanks for your feedback!
