### ISSUE TITLE
[REQUEST] make things persistent

### ISSUE THREAD

**Issue by badrelmers** [lukasbach/yana#3]
**Is your feature request related to a problem? Please describe.**
I cannot explain this without an image:
actually we can change the panel position like that:
![image](https://user-images.githubusercontent.com/40046489/100405133-45731e80-3063-11eb-81e8-410a225f058f.png)

and we can make the dropdown menus in a closed state like that:
![image](https://user-images.githubusercontent.com/40046489/100404896-c4b42280-3062-11eb-96af-600d583f7f39.png)

the problem is that this is not persistent, every time I restart Yana I have to reconfigure those two things again and again

**Describe the solution you'd like**
I hope you can make this persistent after restarts.

thank you.

**Comment by lukasbach** [comment]
Please note that you can remove the sections "Starred items" and "Recent items" from the sidebar altogether by going into the settings, then the tab "Sidebar" and deselecting the options "Show starred items in sidebar" and "Show recently edited items in sidebar", so if you are not using these sections at all, you can just hide them from there.

Persisting the sidebar state (e.g. which folders are open) is actually on my list of todos, so that I'll adress in the future. Thanks for the input.

**Comment by badrelmers** [comment]
> if you are not using these sections at all, you can just hide them from there.

yes I saw those options, but I find this sections useful. I hope it can persist too.

> Persisting the sidebar state (e.g. which folders are open) is actually on my list of todos

that is cool, thank you very much.

**Comment by lukasbach** [comment]
Persisting folders and collapse-state of sidebar headers was added.

Fixed in v1.0.6
